const IATA_BY_CITY: Record<string, string> = {
  delhi: "DEL",
  newdelhi: "DEL",
  mumbai: "BOM",
  bombay: "BOM",
  bangalore: "BLR",
  bengaluru: "BLR",
  chennai: "MAA",
  madras: "MAA",
  kolkata: "CCU",
  calcutta: "CCU",
  hyderabad: "HYD",
  pune: "PNQ",
  ahmedabad: "AMD",
  kochi: "COK",
  cochin: "COK",
  kerala: "COK",
  kozhikode: "CCJ",
  calicut: "CCJ",
  thiruvananthapuram: "TRV",
  trivandrum: "TRV",
  jaipur: "JAI",
  goa: "GOI",
  panaji: "GOI",
  mysore: "MYQ",
  mysuru: "MYQ",
  chandigarh: "IXC",
  lucknow: "LKO",
  varanasi: "VNS",
  indore: "IDR",
  bhubaneswar: "BBI",
  coimbatore: "CJB",
  madurai: "IXM",
  vijayawada: "VGA",
  visakhapatnam: "VTZ",
  patna: "PAT",
  ranchi: "IXR",
  nagpur: "NAG",
  surat: "STV",
  rajkot: "RAJ",
  bhopal: "BHO",
  dehradun: "DED",
  amritsar: "ATQ",
  jodhpur: "JDH",
  udaipur: "UDR",
  guwahati: "GAU",
  shillong: "SHL",
  imphal: "IMF",
  agartala: "IXA",
  gangtok: "PYG",
  siliguri: "IXB",
  portblair: "IXZ",
  andaman: "IXZ",
  srinagar: "SXR",
  leh: "IXL",
  jammu: "IXJ",
};

export function normalizeCityInput(city: string): string {
  return city.toLowerCase().replace(/[^a-z0-9]/g, "");
}

export function lookupIata(city: string): string | null {
  const key = normalizeCityInput(city);
  return IATA_BY_CITY[key] || null;
}
